package com.dj.photobooth.gallery

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

/** Shared filename so both platform factories (AndroidAppDatabaseFactory, IosAppDatabaseFactory) agree on where the DB file lives. */
internal const val DATABASE_FILE_NAME = "photobooth-history.db"

@Database(entities = [HistoryEntry::class], version = 1, exportSchema = true)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun historyDao(): HistoryDao
}

/**
 * Room's KMP codegen requirement, not a design choice of ours: the actual `object`
 * implementations of this are generated by the Room KSP compiler, one per target, and
 * referenced back via [AppDatabase]'s [ConstructedBy] annotation. Every other expect/actual
 * boundary in this file (the database *builder*, see [AppDatabaseFactory]) is a deliberate
 * choice we made instead; this one isn't optional.
 */
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase>

/**
 * Builds the platform [AppDatabase] instance. Not expect/actual - Android needs a `Context`
 * to resolve app-private storage (`context.getDatabasePath`) while iOS needs the app's
 * Documents directory URL; those aren't parameter types an expect/actual signature can share
 * cleanly. Mirrors [com.dj.photobooth.camera.CameraController]'s pattern: a plain commonMain
 * interface, implemented per-platform, constructed at the platform entry point and threaded
 * down - see that interface's doc comment for the same reasoning.
 */
interface AppDatabaseFactory {
    fun create(): AppDatabase
}
